import type { Puzzle } from '@chessy/core'
import { readBoard } from '@chessy/core'

const testPuzzles: Puzzle[] = [
  {
    id: 'test-puzzle-1',
    startBoard: readBoard([
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |bP|  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |bK|',
      '-------------------------',
      '|  |  |  |bR|  |  |wN|wP|',
      '-------------------------',
      '|wB|  |  |  |  |  |wP|wK|',
      '-------------------------',
      '|  |  |bB|bR|wR|  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
    ].join('\n')),
    sideToMove: 'white',
    correctMoves: [
      { from: [4, 6], to: [2, 5], resultCheckState: 'CHECK' },
      { from: [3, 7], to: [2, 7], resultCheckState: 'SAFE' },
      { from: [5, 0], to: [0, 5], resultCheckState: 'CHECKMATE' },
    ]
  },
  {
    id: 'test-puzzle-2',
    startBoard: readBoard([
      '-------------------------',
      '|  |  |  |  |  |  |bQ|bK|',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |wP|  |bP|',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |wQ|wP|',
      '-------------------------',
      '|  |  |  |  |  |wP|wP|  |',
      '-------------------------',
      '|  |  |  |  |wR|  |wK|  |',
      '-------------------------',
    ].join('\n')),
    sideToMove: 'white',
    correctMoves: [
      { from: [7, 4], to: [0, 4], resultCheckState: 'SAFE' },
      { from: [7, 6], to: [7, 4], resultCheckState: 'SAFE' },
      { from: [5, 6], to: [5, 1], resultCheckState: 'CHECKMATE' },
    ]
  },
  {
    id: 'test-puzzle-3',
    startBoard: readBoard([
      '-------------------------',
      '|  |  |  |  |  |bN|  |bR|',
      '-------------------------',
      '|  |  |  |  |  |wN|  |  |',
      '-------------------------',
      '|bP|bP|bP|  |  |  |bR|  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |bK|',
      '-------------------------',
      '|  |  |  |wP|  |wR|  |bP|',
      '-------------------------',
      '|  |  |  |  |  |wP|  |wN|',
      '-------------------------',
      '|wP|wP|  |  |  |wK|  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |wR|  |',
      '-------------------------',
    ].join('\n')),
    sideToMove: 'white',
    correctMoves: [
      { from: [4, 5], to: [3, 5], resultCheckState: 'CHECK' },
      { from: [2, 6], to: [3, 6], resultCheckState: 'SAFE' },
      { from: [3, 5], to: [3, 6], resultCheckState: 'CHECKMATE' },
    ]
  },
  {
    id: 'test-puzzle-4',
    startBoard: readBoard([
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|wR|  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |bP|  |bK|  |  |bB|wN|',
      '-------------------------',
      '|bP|wP|  |wP|  |  |bP|  |',
      '-------------------------',
      '|  |  |  |wK|  |  |  |bP|',
      '-------------------------',
      '|  |  |  |  |  |  |  |wP|',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |wB|  |  |  |',
      '-------------------------',
    ].join('\n')),
    sideToMove: 'white',
    correctMoves: [
      { from: [7, 4], to: [6, 3], resultCheckState: 'SAFE' },
      { from: [2, 6], to: [0, 4], resultCheckState: 'SAFE' },
      { from: [2, 7], to: [3, 5], resultCheckState: 'CHECKMATE' },
    ]
  },
  {
    id: 'test-puzzle-5',
    startBoard: readBoard([
      '-------------------------',
      '|  |  |wB|  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |  |wK|  |  |  |  |',
      '-------------------------',
      '|  |bP|  |  |  |  |  |  |',
      '-------------------------',
      '|  |  |bK|  |  |  |  |  |',
      '-------------------------',
      '|wP|  |  |  |  |wP|  |  |',
      '-------------------------',
      '|  |wB|  |  |  |  |  |  |',
      '-------------------------',
      '|wN|  |  |  |  |wN|  |  |',
      '-------------------------',
    ].join('\n')),
    sideToMove: 'white',
    correctMoves: [
      { from: [0, 2], to: [2, 0], resultCheckState: 'SAFE' },
      { from: [4, 2], to: [5, 3], resultCheckState: 'SAFE' },
      { from: [2, 0], to: [3, 1], resultCheckState: 'CHECKMATE' },
    ]
  },
];

export default testPuzzles
